ww -S > res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
ww -S >> res.out
